Description of get_base_alphas
Home > crp_model_public > helper_functions > get_base_alphas.m
get_base_alphas
PURPOSE
Calculates base alpha params for Dirichlet distributions on each trial
SYNOPSIS
function alphas = get_base_alphas(parms,structure)
DESCRIPTION
 Calculates base alpha params for Dirichlet distributions on each trial
 Base alpha paramaters encode whether each AOI is cued and/or salient on
 each trial.
 Arguments:
  o parms - the cognitive model parameters that define attention to cue
            and salience for this participant.
  o structure -  the experimental settings for this participant
 Returns:
 o alphas - Dirichlet distribution alpha parameters for each trial
CROSS-REFERENCE INFORMATION
This function calls:
iscued Gets whether each AOI is cued on each trial
issal Gets whether each AOI is salient on each trial
This function is called by:
get_alphas Calculates alpha parameters for the Dirichlet distirbutions on each trial
SOURCE CODE
% Calculates base alpha params for Dirichlet distributions on each trial
%
% Base alpha paramaters encode whether each AOI is cued and/or salient on
% each trial.
%
% Arguments:
%  o parms - the cognitive model parameters that define attention to cue
%            and salience for this participant.
%  o structure -  the experimental settings for this participant
%
% Returns:
% o alphas - Dirichlet distribution alpha parameters for each trial
function alphas = get_base_alphas(parms,structure)
cue = parms.cue_p;
sal = parms.sal_p;
boxes = parms.boxes_p;
alphas = sal*issal(structure) + cue*iscued(structure);
%alphas = alphas + ones(size(alphas,1),1)*boxes;
end